- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Dynamic
    name: "{{ public_ip_name }}{{ no }}"
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}{{ no }}"
    virtual_network: "{{ vm_net_name }}"
    subnet: "{{ subnet_name }}"
    public_ip_name: "{{ public_ip_name }}{{ no }}"
    security_group: "{{ security_group_name }}"
