---
- name: create virtual machine
  hosts: azure
  connection: local
  gather_facts: no
  roles:
    - network_assing
    - storage_account
    - centos73

- name: configure virtual machine
  hosts: "{{ host_group }}"
  gather_facts: no
  become: yes
  roles:
    - locale_time
    - selinux_off
    - hadoop-cdh
    - hadoop-hotonworks
    - devtool
    - pip
    - yum_update
    - jdk8
    - spark
    - sbt
    - reboot
    - hadoop-mapreduce
    - npm
    - reboot
