- name: node npm install
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ npm_yum_packages }}"

- name: npm package install
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_packages }}"
