---
#main.yml
- name: get jdk 1.8.0_121
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /opt
    sha256sum: "97e30203f1aef324a07c94d9d078f5d19bb6c50e638e4492722debca588210bc"

- name: get jce_policy-8
  get_url:
    url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /opt
    sha256sum: "f3020a3922efd6626c2fff45695d527f34a8020e938a49292561f18ad1320b59"

- name: unarchive jdk
  command: /usr/bin/tar zxvf /opt/jdk-8u121-linux-x64.tar.gz -C /opt

- name: unarchive jce
  command: /usr/bin/unzip /opt/jce_policy-8.zip -d /opt

- name: jce copy(local_policy.jar)
  command: /usr/bin/cp -f /opt/UnlimitedJCEPolicyJDK8/local_policy.jar /opt/jdk1.8.0_121/jre/lib/security/. 

- name: jce copy(US_export_policy.jar)
  command: /usr/bin/cp -f /opt/UnlimitedJCEPolicyJDK8/US_export_policy.jar /opt/jdk1.8.0_121/jre/lib/security/. 

- name: chwon jdk8
  file:
    owner: root
    group: root
    path: /opt/jdk1.8.0_121
    state: directory
    recurse: yes

- name: remove jdk archive
  file:
    path: /opt/jdk-8u121-linux-x64.tar.gz
    state: absent

- name: remove jce_policy.zip
  file:
    path: /opt/jce_policy-8.zip
    state: absent

- name: remove UnlimitedJCEPolicyJDK8
  file:
    path: /opt/UnlimitedJCEPolicyJDK8
    state: absent

- name: set JDK_PATH
  become: no
  lineinfile:
    dest: /home/centos/.bash_profile
    line: "{{ item }}"
    state: present
  with_items:
      - 'export JAVA_HOME=/opt/jdk1.8.0_121'
      - 'export JAVA_JRE=/opt/jdk1.8.0_121/jre'
      - 'PATH=${JRE_HOME}/bin:${JAVA_HOME}/bin:${PATH}'
