---
#main.yml
- name: download sbt
  get_url:
    url: https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip
    dest: /opt
    sha256sum: "701ac8873b9f91c591c86cbd74b2b7057f9cfeeee374cc9bc07303243b6fb5e7"

- name: unarchive jce
  command: /usr/bin/unzip /opt/sbt-0.13.13.zip -d /opt

- name: chwon sbt
  file:
    owner: root
    group: root
    path: /opt/sbt-launcher-packaging-0.13.13
    state: directory
    recurse: yes

- name: remove sbt
  file:
    path: /opt/sbt-0.13.13.zip
    state: absent

- name: set sbt path
  become: no
  lineinfile:
    dest: /home/centos/.bash_profile
    line: "{{ item }}"
    state: present
  with_items:
      - 'export SBT_HOME=/opt/sbt-launcher-packaging-0.13.13'
      - 'export PATH=${SBT_HOME}/bin:${PATH}'
