---
#main.yml
- name: download sbt
  become: no
  get_url:
    url: https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip
    dest: /home/centos

- name: unarchive jce
  become: no
  command: /usr/bin/unzip /home/centos/sbt-0.13.13.zip -d /home/centos

- name: remove sbt
  file:
    path: /home/centos/sbt-0.13.13.zip
    state: absent

- name: set sbt path
  become: no
  lineinfile:
    dest: /home/centos/.bash_profile
    line: "{{ item }}"
    state: present
  with_items:
      - 'export SBT_HOME=/home/centos/sbt-launcher-packaging-0.13.13'
      - 'export PATH=${SBT_HOME}/bin:${PATH}'
