- name: download hotonworks repo file
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.1.0/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo
  become: yes
  become_user: root
