---
#main.yml
- name: get jdk 1.7.0_80
  get_url:
    url: http://download.oracle.com/otn/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /opt
    sha256sum: "24d885d535739a6b7b54e153919fbbce932a344f5ca3ee5a86b01ac775085863"

- name: get jce_policy-7
  get_url:
    url: http://download.oracle.com/otn-pub/java/jce/7/UnlimitedJCEPolicyJDK7.zip
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /opt
    sha256sum: "7a8d790e7bd9c2f82a83baddfae765797a4a56ea603c9150c87b7cdb7800194d"

- name: unarchive jdk
  command: /usr/bin/tar zxvf /opt/jdk-7u80-linux-x64.tar.gz -C /opt 

- name: unarchive jce
  command: /usr/bin/unzip /opt/UnlimitedJCEPolicyJDK7.zip -d /opt

- name: jce copy(local_policy.jar)
  command: /usr/bin/cp -f /opt/UnlimitedJCEPolicyJDK7/local_policy.jar /opt/jdk1.7.0_80/jre/lib/security/. 

- name: jce copy(US_export_policy.jar)
  command: /usr/bin/cp -f /opt/UnlimitedJCEPolicyJDK7/US_export_policy.jar /opt/jdk1.7.0_80/jre/lib/security/. 

- name: chwon jdk7
  file:
    owner: root
    group: root
    path: /opt/jdk1.7.0_80
    state: directory
    recurse: yes

- name: remove jdk archive
  file:
    path: /opt/jdk-7u80-linux-x64.tar.gz
    state: absent
- name: remove jce_policy.zip
  file:
    path: /opt/UnlimitedJCEPolicyJDK7.zip
    state: absent

- name: remove UnlimitedJCEPolicyJDK7
  file:
    path: /opt/UnlimitedJCEPolicyJDK7
    state: absent

- name: set JDK_PATH
  become: no
  lineinfile:
    dest: /opt/.bash_profile
    line: "{{ item }}"
    state: present
  with_items:
      - 'export JAVA_HOME=/opt/jdk1.7.0_80'
      - 'export JAVA_JRE=/opt/jdk1.7.0_80/jre'
      - 'PATH=${JRE_HOME}/bin:${JAVA_HOME}/bin:${PATH}'
