- name: Create VM with WindowsServer2012r2
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}{{ no }}"
    virtual_network_name: "{{ vm_network_name }}"
    subnet_name: publicNetwork
    network_interface_names: "{{ nic_name }}{{ no }}"
    os_type: Windows
    open_ports:
      - 3389
      - 5986
    storage_container: win2012r2
    storage_blob: "{{ vm_name }}{{ no }}.vhd"
    vm_size: "{{ vm_size }}"
    storage_account_name: "{{ storage_account_name }}"
    public_ip_allocation_method: Dynamic
    admin_username: winadmin
    admin_password: Microsoft1234
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: '2012-R2-Datacenter'
      version: latest
  delegate_to: localhost

- name: Get facts for one virtual network
  register: network_fact
  azure_rm_publicipaddress_facts:
    resource_group: "{{ resource_group }}"
    name: "{{ public_ip_name }}{{ no }}"

- debug:
    var: network_fact

- debug:
    msg: "{{ item.properties.ipAddress }}"
  with_items: "{{azure_publicipaddresses}}"

- name: Add new instance to host group
  add_host:
    hostname: "{{ vm_name }}{{ no }}"
    groupname: "{{ host_group }}"
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/beta"
    ansible_ssh_host: "{{ item.properties.ipAddress }}"
    ansible_ssh_user: centos
  with_items: "{{ azure_publicipaddresses }}"
