---
#main.yml
- name: download spark
  get_url:
    url: http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
    dest: /opt

- name: unarchive spark
  become: yes
  become_user: root
  command: /usr/bin/tar zxvf /opt/spark-2.1.0-bin-hadoop2.7.tgz -C /opt

- name: chwon spark
  file:
    owner: root
    group: root
    path: /opt/spark-2.1.0-bin-hadoop2.7
    state: directory
    recurse: yes

- name: remove spark
  file:
    path: /opt/spark-2.1.0-bin-hadoop2.7.tgz
    state: absent

- name: set spark path
  become: no
  lineinfile:
    destfile: /home/centos/.bash_profile
    line: "{{ item }}" 
    state: present
  with_items:
      - 'export SPARK_HOME=/opt/spark-2.1.0-bin-hadoop2.7'
      - 'PATH=${SPARK_HOME}/bin:${PATH}'
