---
#main.yml
- name: download spark
  become: no
  get_url:
    url: http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
    dest: /home/centos

- name: unarchive spark
  become: no
  command: /usr/bin/tar zxvf /home/centos/spark-2.1.0-bin-hadoop2.7.tgz -C /home/centos

- name: remove spark
  file:
    path: /home/centos/spark-2.1.0-bin-hadoop2.7.tgz
    state: absent

- name: set spark path
  become: no
  lineinfile:
    destfile: /home/centos/.bash_profile
    line: "{{ item }}" 
    state: present
  with_items:
      - 'export SPARK_HOME=/home/centos/spark-2.1.0-bin-hadoop2.7'
      - 'PATH=${SPARK_HOME}/bin:${PATH}'
